### ISSUE TITLE
Wordpress crashes after enabling server-side error tracking (PHP) 

### ISSUE THREAD

**Issue by zeiv** [MindscapeHQ/raygun4wordpress#25] opened 2018-04-26 04:45 UTC
Using the latest versions of Wordpress and Raygun4WP.  I'm on PHP 7.0, cURL is installed, WHM, cPanel etc.  Don't have a full investigation done yet... just wanted to get the issue in right away

It's a 500 error on all pages.

For now this is all I have, noticed this in Raygun around the same time as I was getting errors (all traffic was blocked)

Message: Unexpected token <
at s line null, column null (null:null)

Disabling PHP (server-side) error tracking fixes the issue regardless of other settings

**Comment by samuel-holt** [comment] 2018-05-02 21:45
@zeiv The issue seems to be caused by the use of the deprecated `global` keyword in `main.php`. We'll just need to replace with this with a different approach. We'll let you know once we've pushed a fix for this.

**Comment by redJ4y** [comment] 2023-02-14 00:41
As of version 2.0.0, the use of the `global` keyword has been replaced by a client manager to hold our client instance.

**Closed by redJ4y** 2023-02-14 00:41 UTC
